version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install the AWS cli
          command: |
            sudo apt-get install python-dev
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            aws --version
            aws iam get-user

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            cd src/environments/lambda && npm install

      - run:
          name: Install client dependencies
          command: |
            cd src && npm install

      - save_cache:
          paths:
            - src/environments/lambda/node_modules
            - src/node_modules
          key: v1-dependencies-

      - run:
          name: Deploy application # creates .serverless/stack.json w/ CF stack vars
          command: cd src/environments/lambda && npx sls deploy --verbose --stage pre --no-confirm --force
          no_output_timeout: 30m

      - run:
          name: Create route53 upsert
          command: jq -n --argfile stack .serverless/stack.json -f resources/alias.json -M > .serverless/upsert_alias.json

      - run:
          name: Update route53 & wait
          command: aws route53 change-resource-record-sets --hosted-zone-id $HOSTEDZONEID --change-batch file://.serverless/upsert_alias.json --query 'ChangeInfo.Id' --output text | xargs aws route53 wait resource-record-sets-changed --id
